# POST https://ccs8finalproj-production.up.railway.app/accounts/login/
# Content-Type: application/json

# {
#     "username": "chan",
#     "password": "12321354"
# }


POST http://127.0.0.1:8000/notebook/getNB/
Content-Type: application/json
Authorization: Bearer <token>

{
    "notebook_ID": 12
}
 

# POST https://ccs8finalproj-production.up.railway.app/notebook/post/
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3Mjg5ODE2LCJpYXQiOjE3NDcyODYyMTYsImp0aSI6ImQ2MTIwNTgyNDNjMDQ4MTE5NzU3YzZiOWUzYTNhZGQzIiwidXNlcl9pZCI6MTN9.ExNKd526Ozit0MyZFecF9lgNgsVZTLlHFQdEjk-GsTI

# {
#     "title": "Science Notebook",
#     "pages": [
#         {
#             "title": "Atoms and Molecules",
#             "blocks": [
#                 { "content": "fsfsdf" },
#                 { "content": " i wam you" }
#             ]
#         },
#         {
#             "title": "Hello",
#             "blocks": [
#                 { "content": "Hello world" }
#             ]
#         }
#     ]
# }

# DELETE http://127.0.0.1:8000/notebook/delete/
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2OTY2OTE1LCJpYXQiOjE3NDY5NjMzMTUsImp0aSI6IjEyNWNmZWIwZmMxNjRlMzk5MTJhOTg2ZDA0MzBjYzZlIiwidXNlcl9pZCI6MTN9.avrT2IZ4Js1PUrYpFbl-9If2Ss8CusWknM5c28WoFbs

# {
#     "notebook_ID": 11
# }

# POST http://127.0.0.1:8000/accounts/delete/
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2OTY1NDk5LCJpYXQiOjE3NDY5NjE4OTksImp0aSI6IjdlMWE1N2E2Y2E1ZDQwM2E4OGM3YjU2ZTFkODAwMzYzIiwidXNlcl9pZCI6MTR9.VuRaN8Sse01rZ8QTTxMofdiLLpIcEDLlX7Rg-9e-KeY

# {
#     "password": "vincent123"
# }

# GET http://127.0.0.1:8000/notebook/get/
# Content-Type: application/json
# Authorization: Bearer <token>