# Generated by Django 5.1.7 on 2025-05-01 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userAccount',
            new_name='users',
        ),
    ]
