# Generated by Django 5.1.7 on 2025-05-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_useraccount_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='displayName',
            field=models.CharField(default='User', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
