# Generated by Django 5.1.7 on 2025-05-15 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_users_displayname_alter_users_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='displayName',
        ),
    ]
