# Generated by Django 5.1.7 on 2025-05-04 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_summarizer', '0005_alter_chathistory_user'),
        ('accounts', '0002_rename_useraccount_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chat_histories', to='accounts.users'),
        ),
    ]
