# Generated by Django 5.1.7 on 2025-05-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI_summarizer', '0006_alter_chathistory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='user',
        ),
    ]
