# Generated by Django 5.1.7 on 2025-05-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_notes_timestamp_pages_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
        migrations.AlterField(
            model_name='pages',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
